# Generated by Django 4.0.6 on 2022-07-15 21:21

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Block', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='blocktranslation',
            old_name='contentId',
            new_name='blockTranslationId',
        ),
        migrations.RemoveField(
            model_name='block',
            name='sortOrder',
        ),
        migrations.AddField(
            model_name='blocktranslation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blocktranslation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blocktranslation',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
