# Generated by Django 4.0.6 on 2022-07-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Block', '0002_rename_created_at_block_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='blocktranslation',
            old_name='blockTranslationId',
            new_name='contentId',
        ),
        migrations.RemoveField(
            model_name='blocktranslation',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='blocktranslation',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='block',
            name='sortOrder',
            field=models.IntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='blocktranslation',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
