# Generated by Django 4.0.6 on 2022-07-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Block', '0003_rename_createdat_block_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktranslation',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
