# Generated by Django 4.0.6 on 2022-07-15 02:13

import Customer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerGroup',
            fields=[
                ('customerGroupId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Group Name')),
                ('isDefault', models.BooleanField(default=False, verbose_name='Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255, unique=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, verbose_name='Last Name')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Profile Image')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Id')),
                ('contactNo', models.CharField(max_length=12, unique=True, verbose_name='Contact')),
                ('password', models.CharField(max_length=255, validators=[Customer.models.validate_not_spaces], verbose_name='Password')),
                ('emailVerified', models.BooleanField(default=False, verbose_name='Email Verifiy')),
                ('emailVerifiedDate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Verified Date')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('code', models.CharField(default=0, max_length=10)),
                ('expireDate', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customergroup', verbose_name='Group Name')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('addressId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Adrees Type')),
                ('streetAddress', models.CharField(max_length=255, verbose_name='Street Name')),
                ('houseNo', models.CharField(max_length=255, verbose_name='House No')),
                ('postalCode', models.CharField(max_length=255, verbose_name='Postal Code')),
                ('landmark', models.CharField(max_length=255, verbose_name='Landmark Address')),
                ('isDefault', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='Customer Name')),
            ],
        ),
    ]
