# Generated by Django 4.0.6 on 2022-07-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0002_alter_configuration_fieldtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='value',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=50, verbose_name='Value'),
        ),
    ]
