# Generated by Django 4.0.6 on 2022-07-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0003_configuration_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Value'),
        ),
    ]
